    - name: 'RedEye'
      path: './plugins/siriproxy-redeye'
      reips: { '1': '192.168.69.75',
               '2': '192.168.69.76', 
               '3': '192.168.69.77' } #IP addresses of RedEye

 
